---
- name: Deploy UPaM project as Docker container
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present

    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker.io
        state: present

    - name: Ensure Python Docker module is installed
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Clone GitHub repository
      ansible.builtin.git:
        repo: 'https://github.com/66024996/UPaM.git'
        dest: './UPaM'
        update: yes

    - name: Build Docker image from UPaM
      community.docker.docker_image:
        path: ./UPaM
        name: upam_app
        state: present

    - name: Run UPaM container
      community.docker.docker_container:
        name: upam_container
        image: upam_app
        state: started
        restart_policy: always
        published_ports:
          - 8080:80
